#! /bin/bash
function validIp(){
    [ $# != 1 ] && return 1

    grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$" <<< "$1" && return 0

    return 1
}
# param
[ $# != 1 ] && echo "must offer a address!" && exit 1

echo "$1" | grep "^[0-9].*" >/dev/null 2>&1 \
  && !(validIp $1) && echo "ip $1 is invalid!" && exit 1

# echo "login as root to $1" && ssh -o StrictHostKeyChecking=no root@$1
ssh -o StrictHostKeyChecking=no root@$1


